<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>

<%@ page import="javax.servlet.http.*,javax.servlet.*" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Car Accident Database</title>
</head>
<body align=center>
 <!-- the usual HTML way -->
 <img src="http://i.imgur.com/elgioGy.jpg" alt="logo" width="500" ">


									  
<br>
<form method="get" action="show.jsp" enctype=text/plain>
<p><u>Select Date Range...</u></p>
	Day: <select name="day" id="day_ID" aria-required="true">
  <option value="01">01</option>
  <option value="02">02</option>
  <option value="03">03</option>
  <option value="04">04</option>
  <option value="05">05</option>
  <option value="06">06</option>
  <option value="07">07</option>
  <option value="08">08</option>
  <option value="09">09</option>
  <option value="10">10</option>
  <option value="11">11</option>
  <option value="12">12</option>
  <option value="13">13</option>
  <option value="14">14</option>
  <option value="15">15</option>
  <option value="16">16</option>
  <option value="17">17</option>
  <option value="18">18</option>
  <option value="19">19</option>
  <option value="20">20</option>
  <option value="21">21</option>
  <option value="22">22</option>
  <option value="23">23</option>
  <option value="24">24</option>
  <option value="25">25</option>
  <option value="26">26</option>
  <option value="27">27</option>
  <option value="28">28</option>
  <option value="29">29</option>
  <option value="30">30</option>
  <option value="31">31</option>
</select>

Month: <select method ="post" name="month" id="month_ID" aria-required="true">
  
  <option value="01">January</option>
  <option value="02">February</option>
  <option value="03">March</option>
  <option value="04">April</option>
	  <option value="05">May</option>
  <option value="06">June</option>
  <option value="07">July</option>
  <option value="08">August</option>
	  <option value="09">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
	  </select>
	   
	  Year: <select method="post" name="year" id="year_ID" aria-required="true">
  <option value="2012">2012</option>
  <option value="2013">2013</option>
  <option value="2014">2014</option>
  <option value="2015">2015</option>
</select>
<p class="tab" align="center">TO</p>
Day:
<select name="day2" id="day_ID" aria-required="true">
  <option value="01">01</option>
  <option value="02">02</option>
  <option value="03">03</option>
  <option value="04">04</option>
  <option value="05">05</option>
  <option value="06">06</option>
  <option value="07">07</option>
  <option value="08">08</option>
  <option value="09">09</option>
  <option value="10">10</option>
  <option value="11">11</option>
  <option value="12">12</option>
  <option value="13">13</option>
  <option value="14">14</option>
  <option value="15">15</option>
  <option value="16">16</option>
  <option value="17">17</option>
  <option value="18">18</option>
  <option value="19">19</option>
  <option value="20">20</option>
  <option value="21">21</option>
  <option value="22">22</option>
  <option value="23">23</option>
  <option value="24">24</option>
  <option value="25">25</option>
  <option value="26">26</option>
  <option value="27">27</option>
  <option value="28">28</option>
  <option value="29">29</option>
  <option value="30">30</option>
  <option value="31">31</option>
</select>

Month: <select method ="post" name="month2" id="month_ID" aria-required="true">
  
  <option value="01">January</option>
  <option value="02">February</option>
  <option value="03">March</option>
  <option value="04">April</option>
	  <option value="05">May</option>
  <option value="06">June</option>
  <option value="07">July</option>
  <option value="08">August</option>
	  <option value="09">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
	  </select>
	   
	  Year: <select method="post" name="year2" id="year_ID" aria-required="true">
  <option value="2012">2012</option>
  <option value="2013">2013</option>
  <option value="2014">2014</option>
  <option value="2015">2015</option>
</select>
<br></br>

  City: <select name="`city/town`" aria-required="true">
		<option value="absecon">Absecon</option>
<option value="allamuchy">Allamuchy</option>
<option value="allendale">Allendale</option>
<option value="allenhurst">Allenhurst</option>
<option value="allentown">Allentown</option>
<option value="allenwood">Allenwood</option>
<option value="alloway">Alloway</option>
<option value="alpine">Alpine</option>
<option value="andover">Andover</option>
<option value="annandale">Annandale</option>
<option value="asbury">Asbury</option>
<option value="asburypark">Asbury Park</option>
<option value="atco">Atco</option>
<option value="atlantichighlands">Atlantic Highlands</option>
<option value="audubon">Audubon</option>
<option value="augusta">Augusta</option>
<option value="avalon">Avalon</option>
<option value="avenel">Avenel</option>
<option value="avonbythesea">Avon By The Sea</option>
<option value="barnegat">Barnegat</option>
<option value="barnegatlight">Barnegat Light</option>
<option value="barrington">Barrington</option>
<option value="baskingridge">Basking Ridge</option>
<option value="bassriver">Bass River</option>
<option value="bayonne">Bayonne</option>
<option value="bayville">Bayville</option>
<option value="beachhaven">Beach Haven</option>
<option value="beachwood">Beachwood</option>
<option value="bedminster">Bedminster</option>
<option value="bellmawr">Bellmawr</option>
<option value="belmar">Belmar</option>
<option value="bergenfield">Bergenfield</option>
<option value="berkeley">Berkeley</option>
<option value="berkeleyheights">Berkeley Heights</option>
<option value="berlin">Berlin</option>
<option value="bernards">Bernards</option>
<option value="bernardsville">Bernardsville</option>
<option value="beverly">Beverly</option>
<option value="birmingham">Birmingham</option>
<option value="blackwood">Blackwood</option>
<option value="blairstown">Blairstown</option>
<option value="blawenburg">Blawenburg</option>
<option value="bloomfield">Bloomfield</option>
<option value="bloomingdale">Bloomingdale</option>
<option value="bloomsbury">Bloomsbury</option>
<option value="bogota">Bogota</option>
<option value="boonton">Boonton</option>
<option value="bordentown">Bordentown</option>
<option value="boundbrook">Bound Brook</option>
<option value="bradleybeach">Bradley Beach</option>
<option value="branchville">Branchville</option>
<option value="brick">Brick</option>
<option value="bridgeport">Bridgeport</option>
<option value="bridgeton">Bridgeton</option>
<option value="bridgewater">Bridgewater</option>
<option value="brielle">Brielle</option>
<option value="brigantine">Brigantine</option>
<option value="broadway">Broadway</option>
<option value="brownsmills">Browns Mills</option>
<option value="buddlake">Budd Lake</option>
<option value="buena">Buena</option>
<option value="burlington">Burlington</option>
<option value="butler">Butler</option>
<option value="buttzville">Buttzville</option>
<option value="caldwell">Caldwell</option>
<option value="califon">Califon</option>
<option value="capemay">Cape May</option>
<option value="capemaycourthouse">Cape May Court House</option>
<option value="capemaypoint">Cape May Point</option>
<option value="carlstadt">Carlstadt</option>
<option value="carteret">Carteret</option>
<option value="cedargrove">Cedar Grove</option>
<option value="cedarknolls">Cedar Knolls</option>
<option value="cedarville">Cedarville</option>
<option value="changewater">Changewater</option>
<option value="chatham">Chatham</option>
<option value="chatsworth">Chatsworth</option>
<option value="chester">Chester</option>
<option value="city/town">city/town</option>
<option value="clark">Clark</option>
<option value="clarksboro">Clarksboro</option>
<option value="clarksburg">Clarksburg</option>
<option value="clayton">Clayton</option>
<option value="clementon">Clementon</option>
<option value="cliffsidepark">Cliffside Park</option>
<option value="clifton">Clifton</option>
<option value="clinton">Clinton</option>
<option value="closter">Closter</option>
<option value="cologne">Cologne</option>
<option value="coltsneck">Colts Neck</option>
<option value="columbia">Columbia</option>
<option value="columbus">Columbus</option>
<option value="cookstown">Cookstown</option>
<option value="cranbury">Cranbury</option>
<option value="cranford">Cranford</option>
<option value="creamridge">Cream Ridge</option>
<option value="cresskill">Cresskill</option>
<option value="deepwater">Deepwater</option>
<option value="deerfieldstreet">Deerfield Street</option>
<option value="delaware">Delaware</option>
<option value="delmont">Delmont</option>
<option value="demarest">Demarest</option>
<option value="denville">Denville</option>
<option value="dividingcreek">Dividing Creek</option>
<option value="dorchester">Dorchester</option>
<option value="dorothy">Dorothy</option>
<option value="dover">Dover</option>
<option value="downe">Downe</option>
<option value="dumont">Dumont</option>
<option value="dunellen">Dunellen</option>
<option value="eastamwell">East Amwell</option>
<option value="eastbrunswick">East Brunswick</option>
<option value="eastorange">East Orange</option>
<option value="edgewater">Edgewater</option>
<option value="edison">Edison</option>
<option value="eggharborcity">Egg Harbor City</option>
<option value="eggharbortownship">Egg Harbor Township</option>
<option value="elizabeth">Elizabeth</option>
<option value="elmer">Elmer</option>
<option value="elmwoodpark">Elmwood Park</option>
<option value="elwood">Elwood</option>
<option value="elwood-magnolia">Elwood-Magnolia</option>
<option value="emerson">Emerson</option>
<option value="englewoodcliffs">Englewood Cliffs</option>
<option value="englishtown">Englishtown</option>
<option value="essexfells">Essex Fells</option>
<option value="estellmanor">Estell Manor</option>
<option value="ewan">Ewan</option>
<option value="fairhaven">Fair Haven</option>
<option value="fairlawn">Fair Lawn</option>
<option value="fairfield">Fairfield</option>
<option value="fairton">Fairton</option>
<option value="fairview">Fairview</option>
<option value="fanwood">Fanwood</option>
<option value="flagtown">Flagtown</option>
<option value="flanders">Flanders</option>
<option value="flemington">Flemington</option>
<option value="florence">Florence</option>
<option value="fords">Fords</option>
<option value="forkedriver">Forked River</option>
<option value="fortlee">Fort Lee</option>
<option value="fortmonmouth">Fort Monmouth</option>
<option value="fortescue">Fortescue</option>
<option value="franklin">Franklin</option>
<option value="franklinlakes">Franklin Lakes</option>
<option value="franklinpark">Franklin Park</option>
<option value="franklinville">Franklinville</option>
<option value="frenchtown">Frenchtown</option>
<option value="garfield">Garfield</option>
<option value="garwood">Garwood</option>
<option value="gibbsboro">Gibbsboro</option>
<option value="gibbstown">Gibbstown</option>
<option value="gillette">Gillette</option>
<option value="gladstone">Gladstone</option>
<option value="glasser">Glasser</option>
<option value="glengardner">Glen Gardner</option>
<option value="glenridge">Glen Ridge</option>
<option value="glendora">Glendora</option>
<option value="glenwood">Glenwood</option>
<option value="gloucestercity">Gloucester City</option>
<option value="goshen">Goshen</option>
<option value="greatmeadows">Great Meadows</option>
<option value="greencreek">Green Creek</option>
<option value="greenvillage">Green Village</option>
<option value="greendell">Greendell</option>
<option value="greenwich">Greenwich</option>
<option value="grenloch">Grenloch</option>
<option value="hackensack">Hackensack</option>
<option value="hackettstown">Hackettstown</option>
<option value="haddonheights">Haddon Heights</option>
<option value="haddonfield">Haddonfield</option>
<option value="hamburg">Hamburg</option>
<option value="hammonton">Hammonton</option>
<option value="hampton">Hampton</option>
<option value="hancocksbridge">Hancocks Bridge</option>
<option value="harringtonpark">Harrington Park</option>
<option value="harrisonville">Harrisonville</option>
<option value="hasbrouckheights">Hasbrouck Heights</option>
<option value="haskell">Haskell</option>
<option value="hawthorne">Hawthorne</option>
<option value="hazlet">Hazlet</option>
<option value="helmetta">Helmetta</option>
<option value="hewitt">Hewitt</option>
<option value="hibernia">Hibernia</option>
<option value="highlandlakes">Highland Lakes</option>
<option value="highlandpark">Highland Park</option>
<option value="highlands">Highlands</option>
<option value="hightstown">Hightstown</option>
<option value="hillsdale">Hillsdale</option>
<option value="hillside">Hillside</option>
<option value="hohokus">Ho Ho Kus</option>
<option value="ho-ho-kus">Ho-Ho-Kus</option>
<option value="holmdel">Holmdel</option>
<option value="hopatcong">Hopatcong</option>
<option value="hopewell">Hopewell</option>
<option value="howell">Howell</option>
<option value="imlaystown">Imlaystown</option>
<option value="ironia">Ironia</option>
<option value="irvington">Irvington</option>
<option value="iselin">Iselin</option>
<option value="jackson">Jackson</option>
<option value="jerseycity">Jersey City</option>
<option value="jobstown">Jobstown</option>
<option value="johnsonburg">Johnsonburg</option>
<option value="keansburg">Keansburg</option>
<option value="kearny">Kearny</option>
<option value="keasbey">Keasbey</option>
<option value="kendallpark">Kendall Park</option>
<option value="kenilworth">Kenilworth</option>
<option value="kenvil">Kenvil</option>
<option value="keyport">Keyport</option>
<option value="kingston">Kingston</option>
<option value="lafayette">Lafayette</option>
<option value="lakehiawatha">Lake Hiawatha</option>
<option value="lakehurst">Lakehurst</option>
<option value="lakewood">Lakewood</option>
<option value="lambertville">Lambertville</option>
<option value="landisville">Landisville</option>
<option value="lawnside">Lawnside</option>
<option value="layton">Layton</option>
<option value="lebanon">Lebanon</option>
<option value="ledgewood">Ledgewood</option>
<option value="leedspoint">Leeds Point</option>
<option value="leesburg">Leesburg</option>
<option value="leonia">Leonia</option>
<option value="libertycorner">Liberty Corner</option>
<option value="lincolnpark">Lincoln Park</option>
<option value="lincroft">Lincroft</option>
<option value="linden">Linden</option>
<option value="littlefalls">Little Falls</option>
<option value="littleferry">Little Ferry</option>
<option value="littlesilver">Little Silver</option>
<option value="littleyork">Little York</option>
<option value="longbranch">Long Branch</option>
<option value="longvalley">Long Valley</option>
<option value="longport">Longport</option>
<option value="lumberton">Lumberton</option>
<option value="lyndhurst">Lyndhurst</option>
<option value="lyons">Lyons</option>
<option value="madison">Madison</option>
<option value="magnolia">Magnolia</option>
<option value="mahwah">Mahwah</option>
<option value="malaga">Malaga</option>
<option value="manasquan">Manasquan</option>
<option value="mantoloking">Mantoloking</option>
<option value="manville">Manville</option>
<option value="mapleshade">Maple Shade</option>
<option value="margatecity">Margate City</option>
<option value="marlboro">Marlboro</option>
<option value="marlton">Marlton</option>
<option value="marmora">Marmora</option>
<option value="martinsville">Martinsville</option>
<option value="matawan">Matawan</option>
<option value="mauriceriver">Maurice River</option>
<option value="mayslanding">Mays Landing</option>
<option value="mcafee">McAfee</option>
<option value="medford">Medford</option>
<option value="mendham">Mendham</option>
<option value="merchantville">Merchantville</option>
<option value="metuchen">Metuchen</option>
<option value="mickleton">Mickleton</option>
<option value="middletown">Middletown</option>
<option value="middleville">Middleville</option>
<option value="midlandpark">Midland Park</option>
<option value="milford">Milford</option>
<option value="millburn">Millburn</option>
<option value="millington">Millington</option>
<option value="millstone">Millstone</option>
<option value="milltown">Milltown</option>
<option value="millville">Millville</option>
<option value="milmay">Milmay</option>
<option value="minehill">Mine Hill</option>
<option value="minotola">Minotola</option>
<option value="mizpah">Mizpah</option>
<option value="monmouthbeach">Monmouth Beach</option>
<option value="monroeville">Monroeville</option>
<option value="montague">Montague</option>
<option value="montclair">Montclair</option>
<option value="montvale">Montvale</option>
<option value="moonachie">Moonachie</option>
<option value="morganville">Morganville</option>
<option value="morrisplains">Morris Plains</option>
<option value="mountephraim">Mount Ephraim</option>
<option value="mountlaurel">Mount Laurel</option>
<option value="mountroyal">Mount Royal</option>
<option value="mounttabor">Mount Tabor</option>
<option value="mullicahill">Mullica Hill</option>
<option value="nationalpark">National Park</option>
<option value="navesink">Navesink</option>
<option value="neptune">Neptune</option>
<option value="netcong">Netcong</option>
<option value="newbrunswick">New Brunswick</option>
<option value="newgretna">New Gretna</option>
<option value="newlisbon">New Lisbon</option>
<option value="newmilford">New Milford</option>
<option value="newprovidence">New Providence</option>
<option value="newvernon">New Vernon</option>
<option value="newyork">New York</option>
<option value="newark">Newark</option>
<option value="newfield">Newfield</option>
<option value="newton">Newton</option>
<option value="norma">Norma</option>
<option value="northarlington">North Arlington</option>
<option value="northbergen">North Bergen</option>
<option value="northbrunswick">North Brunswick</option>
<option value="northfield">Northfield</option>
<option value="northvale">Northvale</option>
<option value="norwood">Norwood</option>
<option value="nutley">Nutley</option>
<option value="oakridge">Oak Ridge</option>
<option value="oakhurst">Oakhurst</option>
<option value="oakland">Oakland</option>
<option value="oaklyn">Oaklyn</option>
<option value="oceancity">Ocean City</option>
<option value="oceangate">Ocean Gate</option>
<option value="oceangrove">Ocean Grove</option>
<option value="oceanview">Ocean View</option>
<option value="oceanville">Oceanville</option>
<option value="ogdensburg">Ogdensburg</option>
<option value="oldbridge">Old Bridge</option>
<option value="oldwick">Oldwick</option>
<option value="oradell">Oradell</option>
<option value="orange">Orange</option>
<option value="oxford">Oxford</option>
<option value="palisadespark">Palisades Park</option>
<option value="palmyra">Palmyra</option>
<option value="paramus">Paramus</option>
<option value="parkridge">Park Ridge</option>
<option value="parlin">Parlin</option>
<option value="parsippany">Parsippany</option>
<option value="paterson">Paterson</option>
<option value="peapack">Peapack</option>
<option value="peapackandgladstone">Peapack and Gladstone</option>
<option value="pedricktown">Pedricktown</option>
<option value="pemberton">Pemberton</option>
<option value="pennington">Pennington</option>
<option value="pequannock">Pequannock</option>
<option value="perrineville">Perrineville</option>
<option value="perthamboy">Perth Amboy</option>
<option value="phillipsburg">Phillipsburg</option>
<option value="picatinnyarsenal">Picatinny Arsenal</option>
<option value="pinebeach">Pine Beach</option>
<option value="pinebrook">Pine Brook</option>
<option value="piscataway">Piscataway</option>
<option value="pitman">Pitman</option>
<option value="pittstown">Pittstown</option>
<option value="plainsboro">Plainsboro</option>
<option value="pleasantville">Pleasantville</option>
<option value="pointpleasantbeach">Point Pleasant Beach</option>
<option value="pomona">Pomona</option>
<option value="pomptonlakes">Pompton Lakes</option>
<option value="pomptonplains">Pompton Plains</option>
<option value="portelizabeth">Port Elizabeth</option>
<option value="portmonmouth">Port Monmouth</option>
<option value="portmurray">Port Murray</option>
<option value="portnorris">Port Norris</option>
<option value="portreading">Port Reading</option>
<option value="portrepublic">Port Republic</option>
<option value="pottersville">Pottersville</option>
<option value="princeton">Princeton</option>
<option value="princetonjunction">Princeton Junction</option>
<option value="quinton">Quinton</option>
<option value="ramsey">Ramsey</option>
<option value="rancocas">Rancocas</option>
<option value="randolph">Randolph</option>
<option value="raritan">Raritan</option>
<option value="readington">Readington</option>
<option value="redbank">Red Bank</option>
<option value="richland">Richland</option>
<option value="richwood">Richwood</option>
<option value="ridgefieldpark">Ridgefield Park</option>
<option value="ridgewood">Ridgewood</option>
<option value="ringoes">Ringoes</option>
<option value="ringwood">Ringwood</option>
<option value="riveredge">River Edge</option>
<option value="riverside">Riverside</option>
<option value="riverton">Riverton</option>
<option value="rochellepark">Rochelle Park</option>
<option value="rockyhill">Rocky Hill</option>
<option value="roebling">Roebling</option>
<option value="roosevelt">Roosevelt</option>
<option value="roseland">Roseland</option>
<option value="roselle">Roselle</option>
<option value="rosellepark">Roselle Park</option>
<option value="rosemont">Rosemont</option>
<option value="rosenhayn">Rosenhayn</option>
<option value="rumson">Rumson</option>
<option value="runnemede">Runnemede</option>
<option value="rutherford">Rutherford</option>
<option value="saddleriver">Saddle River</option>
<option value="salem">Salem</option>
<option value="sayreville">Sayreville</option>
<option value="schooleysmountain">Schooleys Mountain</option>
<option value="scotchplains">Scotch Plains</option>
<option value="seagirt">Sea Girt</option>
<option value="seaislecity">Sea Isle City</option>
<option value="seasideheights">Seaside Heights</option>
<option value="secaucus">Secaucus</option>
<option value="sergeantsville">Sergeantsville</option>
<option value="sewaren">Sewaren</option>
<option value="sewell">Sewell</option>
<option value="shorthills">Short Hills</option>
<option value="shrewsbury">Shrewsbury</option>
<option value="sicklerville">Sicklerville</option>
<option value="somerdale">Somerdale</option>
<option value="somerspoint">Somers Point</option>
<option value="somerset">Somerset</option>
<option value="southamboy">South Amboy</option>
<option value="southboundbrook">South Bound Brook</option>
<option value="southdennis">South Dennis</option>
<option value="southorange">South Orange</option>
<option value="southplainfield">South Plainfield</option>
<option value="southriver">South River</option>
<option value="southseaville">South Seaville</option>
<option value="springlake">Spring Lake</option>
<option value="springfield">Springfield</option>
<option value="stanhope">Stanhope</option>
<option value="stanton">Stanton</option>
<option value="stewartsville">Stewartsville</option>
<option value="stockton">Stockton</option>
<option value="stoneharbor">Stone Harbor</option>
<option value="strathmere">Strathmere</option>
<option value="succasunna">Succasunna</option>
<option value="summit">Summit</option>
<option value="swartswood">Swartswood</option>
<option value="swedesboro">Swedesboro</option>
<option value="teaneck">Teaneck</option>
<option value="tenafly">Tenafly</option>
<option value="tennent">Tennent</option>
<option value="teterboro">Teterboro</option>
<option value="threebridges">Three Bridges</option>
<option value="titusville">Titusville</option>
<option value="tomsriver">Toms River</option>
<option value="totowa">Totowa</option>
<option value="towaco">Towaco</option>
<option value="tranquility">Tranquility</option>
<option value="tuckahoe">Tuckahoe</option>
<option value="tuckerton">Tuckerton</option>
<option value="union">Union</option>
<option value="unioncity">Union City</option>
<option value="vauxhall">Vauxhall</option>
<option value="vernon">Vernon</option>
<option value="verona">Verona</option>
<option value="vienna">Vienna</option>
<option value="vincentown">Vincentown</option>
<option value="vineland">Vineland</option>
<option value="voorhees">Voorhees</option>
<option value="waldwick">Waldwick</option>
<option value="wallington">Wallington</option>
<option value="wallpackcenter">Wallpack Center</option>
<option value="wanaque">Wanaque</option>
<option value="waretown">Waretown</option>
<option value="warren">Warren</option>
<option value="washington">Washington</option>
<option value="waterfordworks">Waterford Works</option>
<option value="wayne">Wayne</option>
<option value="westberlin">West Berlin</option>
<option value="westcreek">West Creek</option>
<option value="westlongbranch">West Long Branch</option>
<option value="westnewyork">West New York</option>
<option value="westorange">West Orange</option>
<option value="westfield">Westfield</option>
<option value="westville">Westville</option>
<option value="westwood">Westwood</option>
<option value="whitehousestation">Whitehouse Station</option>
<option value="whitesboro">Whitesboro</option>
<option value="whiting">Whiting</option>
<option value="wickatunk">Wickatunk</option>
<option value="wildwood">Wildwood</option>
<option value="williamstown">Williamstown</option>
<option value="willingboro">Willingboro</option>
<option value="windsor">Windsor</option>
<option value="woodridge">Wood Ridge</option>
<option value="woodbine">Woodbine</option>
<option value="woodbridge">Woodbridge</option>
<option value="woodbury">Woodbury</option>
<option value="woodburyheights">Woodbury Heights</option>
<option value="woodclifflake">Woodcliff Lake</option>
<option value="woodstown">Woodstown</option>
<option value="wrightstown">Wrightstown</option>
<option value="wyckoff">Wyckoff </option>  
 </select> 
 
<p><u>Please select the data you want displayed...</u></p>

<div name="checkbox_attr" action="check_box.asp">
			<input type="checkbox" name="id" value="age">Age
			<input type="checkbox" name="id" value="gender">Gender  
			<input type="checkbox" name="id" value="street">Street
			<input type="checkbox" name="id" value="`city/town`">City/Town
			<input type="checkbox" name="id" value="DUI">DUI 
			<input type="checkbox" name="id" value="time">Time<br>
			<input type="checkbox" name="id" value="`make/model`">Make/Model
			<input type="checkbox" name="id" value="safety_rating">Safety Rating 
			</div>

  <input type="submit" value="Search for Data" />
</form>
<br>

<p><font size="5"><u>Get Insurance Premium Esimate...</u></font></p>
<form method="get" action="get.jsp" enctype=text/plain>
  </select>
  Make & Model: <select name="`make/model`" aria-required="true">
 <option value="astonmartindb9coupe">ASTON MARTIN DB9 COUPE</option>
<option value="astonmartindb9coupemanual">ASTON MARTIN DB9 COUPE MANUAL</option>
<option value="astonmartindb9volante">ASTON MARTIN DB9 VOLANTE</option>
<option value="astonmartinv12vanquishs">ASTON MARTIN V12 VANQUISH S</option>
<option value="astonmartinv8vantage">ASTON MARTIN V8 VANTAGE</option>
<option value="audia3">AUDI A3</option>
<option value="audia4">AUDI A4</option>
<option value="audia4avantquattro">AUDI A4 AVANT QUATTRO</option>
<option value="audia4cabriolet">AUDI A4 CABRIOLET</option>
<option value="audia4cabrioletquattro">AUDI A4 CABRIOLET QUATTRO</option>
<option value="audia4quattro">AUDI A4 QUATTRO</option>
<option value="audia6">AUDI A6</option>
<option value="audia6avantquattro">AUDI A6 AVANT QUATTRO</option>
<option value="audia6quattro">AUDI A6 QUATTRO</option>
<option value="audigti">AUDI GTI</option>
<option value="audipassat">AUDI PASSAT</option>
<option value="audis4">AUDI S4</option>
<option value="audis4avant">AUDI S4 AVANT</option>
<option value="audittcoupe">AUDI TT COUPE</option>
<option value="audittroadster">AUDI TT ROADSTER</option>
<option value="bentleymotorsltd.bentleyarnage">BENTLEY MOTORS LTD. BENTLEY ARNAGE</option>
<option value="bentleymotorsltd.continentalflyingspur">BENTLEY MOTORS LTD. CONTINENTAL FLYING SPUR</option>
<option value="bentleymotorsltd.continentalgt">BENTLEY MOTORS LTD. CONTINENTAL GT</option>
<option value="bmw325i">BMW 325I</option>
<option value="bmw325xi">BMW 325XI</option>
<option value="bmw325xisportwagon">BMW 325XI SPORT WAGON</option>
<option value="bmw330ciconvertible">BMW 330CI CONVERTIBLE</option>
<option value="bmw330i">BMW 330I</option>
<option value="bmw330xi">BMW 330XI</option>
<option value="bmw525i">BMW 525I</option>
<option value="bmw525xi">BMW 525XI</option>
<option value="bmw530i">BMW 530I</option>
<option value="bmw530xi">BMW 530XI</option>
<option value="bmw530xisportwagon">BMW 530XI SPORT WAGON</option>
<option value="bmw550i">BMW 550I</option>
<option value="bmw650ci">BMW 650CI</option>
<option value="bmw650ciconvertible">BMW 650CI CONVERTIBLE</option>
<option value="bmw750li">BMW 750LI</option>
<option value="bmwm3">BMW M3</option>
<option value="bmwm3convertible">BMW M3 CONVERTIBLE</option>
<option value="bmwm5">BMW M5</option>
<option value="bmwm6">BMW M6</option>
<option value="bmwminicooper">BMW MINI COOPER</option>
<option value="bmwminicooperconvertible">BMW MINI COOPER CONVERTIBLE</option>
<option value="bmwminicoopers">BMW MINI COOPER S</option>
<option value="bmwminicoopersconvertible">BMW MINI COOPER S CONVERTIBLE</option>
<option value="bmwx3">BMW X3</option>
<option value="bmwx5">BMW X5</option>
<option value="bmwx54.8is">BMW X5 4.8IS</option>
<option value="bmwz43.0sicoupe">BMW Z4 3.0 SI COUPE</option>
<option value="bmwz43.0i">BMW Z4 3.0I</option>
<option value="bmwz43.0si">BMW Z4 3.0SI</option>
<option value="bmwz4mroadster">BMW Z4 M ROADSTER</option>
<option value="bugattiautomobiless.a.s.veyron">Bugatti Automobiles S.A.S. VEYRON</option>
<option value="daimlerchrysler300c/srt-8">DaimlerChrysler 300C/SRT-8</option>
<option value="daimlerchryslercaravan2wd">DaimlerChrysler CARAVAN 2WD</option>
<option value="daimlerchryslercharger">DaimlerChrysler CHARGER</option>
<option value="daimlerchryslercommander4wd">DaimlerChrysler COMMANDER 4WD</option>
<option value="daimlerchryslercrossfireroadster">DaimlerChrysler CROSSFIRE ROADSTER</option>
<option value="daimlerchryslerdurango2wd">DaimlerChrysler DURANGO 2WD</option>
<option value="daimlerchryslerdurango4wd">DaimlerChrysler DURANGO 4WD</option>
<option value="daimlerchryslergrandcherokee2wd">DaimlerChrysler GRAND CHEROKEE 2WD</option>
<option value="daimlerchryslergrandcherokee4wd">DaimlerChrysler GRAND CHEROKEE 4WD</option>
<option value="daimlerchryslerliberty/cherokee2wd">DaimlerChrysler LIBERTY/CHEROKEE 2WD</option>
<option value="daimlerchryslerliberty/cherokee4wd">DaimlerChrysler LIBERTY/CHEROKEE 4WD</option>
<option value="daimlerchryslerpacifica2wd">DaimlerChrysler PACIFICA 2WD</option>
<option value="daimlerchryslerpacificaawd">DaimlerChrysler PACIFICA AWD</option>
<option value="daimlerchryslerram1500pickup2wd">DaimlerChrysler RAM 1500 PICKUP 2WD</option>
<option value="daimlerchryslerram1500pickup4wd">DaimlerChrysler RAM 1500 PICKUP 4WD</option>
<option value="daimlerchryslersebring4-dr">DaimlerChrysler SEBRING 4-DR</option>
<option value="daimlerchryslerstratus4-dr">DaimlerChrysler STRATUS 4-DR</option>
<option value="daimlerchryslerviperconvertible">DaimlerChrysler VIPER CONVERTIBLE</option>
<option value="daimlerchryslerwrangler/tj4wd">DaimlerChrysler WRANGLER/TJ 4WD</option>
<option value="ferrarif430">FERRARI F430</option>
<option value="ferrariferrari612scaglietti">FERRARI FERRARI 612 SCAGLIETTI</option>
<option value="ferrariferrarif141">FERRARI FERRARI F141</option>
<option value="fordb40004wd">Ford B4000 4WD</option>
<option value="fordcrownvictoriapolice">Ford CROWN VICTORIA POLICE</option>
<option value="forde150clubwagon">Ford E150 CLUB WAGON</option>
<option value="forde150econoline2wd">Ford E150 ECONOLINE 2WD</option>
<option value="fordescape4wd">Ford ESCAPE 4WD</option>
<option value="fordescapefwd">Ford ESCAPE FWD</option>
<option value="fordescapehybrid4wd">Ford ESCAPE HYBRID 4WD</option>
<option value="fordexpedition2wd">Ford EXPEDITION 2WD</option>
<option value="fordexplorer2wd">Ford EXPLORER 2WD</option>
<option value="fordexplorer4wd">Ford EXPLORER 4WD</option>
<option value="fordf150ffv2wd">Ford F150 FFV  2WD</option>
<option value="fordf150ffv4wd">Ford F150 FFV  4WD</option>
<option value="fordf150pickup2wd">Ford F150 PICKUP 2WD</option>
<option value="fordf150pickup4wd">Ford F150 PICKUP 4WD</option>
<option value="fordfivehundredawd">Ford FIVE HUNDRED AWD</option>
<option value="fordfocusfwd">Ford FOCUS  FWD</option>
<option value="fordfocusstationwag">Ford FOCUS STATION WAG</option>
<option value="fordfreestarwagonfwd">Ford FREESTAR WAGON FWD</option>
<option value="fordfreestyleawd">Ford FREESTYLE AWD</option>
<option value="fordgrandmarquis">Ford GRAND MARQUIS</option>
<option value="fordgt2wd">Ford GT        2WD</option>
<option value="fordls">Ford LS</option>
<option value="fordmarklt">Ford MARK LT</option>
<option value="fordmilan">Ford MILAN</option>
<option value="fordmontereywagonfwd">Ford MONTEREY WAGON FWD</option>
<option value="fordmountaineer4wd">Ford MOUNTAINEER 4WD</option>
<option value="fordmustang">Ford MUSTANG</option>
<option value="fordnavigator2wd">Ford NAVIGATOR 2WD</option>
<option value="fordrangerpickup2wd">Ford RANGER PICKUP 2WD</option>
<option value="fordrangerpickup4wd">Ford RANGER PICKUP 4WD</option>
<option value="fordtaurus">Ford TAURUS</option>
<option value="fordtowncar">Ford TOWN CAR</option>
<option value="fordzephyr">Ford ZEPHYR</option>
<option value="fujiheavyindb9tribecaawd">FUJI HEAVY IND B9 TRIBECA AWD</option>
<option value="fujiheavyindbajaawd">FUJI HEAVY IND BAJA AWD</option>
<option value="fujiheavyindforesterawd">FUJI HEAVY IND FORESTER AWD</option>
<option value="fujiheavyindimprezaawd">FUJI HEAVY IND IMPREZA AWD</option>
<option value="fujiheavyindimprezawgn/outbacksptawd">FUJI HEAVY IND IMPREZA WGN/OUTBACK SPT AWD</option>
<option value="fujiheavyindlegacyawd">FUJI HEAVY IND LEGACY AWD</option>
<option value="fujiheavyindlegacywagonawd">FUJI HEAVY IND LEGACY WAGON AWD</option>
<option value="fujiheavyindoutbackawd">FUJI HEAVY IND OUTBACK AWD</option>
<option value="fujiheavyindoutbackwagonawd">FUJI HEAVY IND OUTBACK WAGON AWD</option>
<option value="gm9-3convertible">GM 9-3 CONVERTIBLE</option>
<option value="gm9-3sportsedan">GM 9-3 SPORT SEDAN</option>
<option value="gm9-5sedan">GM 9-5 SEDAN</option>
<option value="gmc15silveradohybrid2wd">GM C15 SILVERADO HYBRID 2WD</option>
<option value="gmc1500suburban2wd">GM C1500 SUBURBAN 2WD</option>
<option value="gmc1500tahoe2wd">GM C1500 TAHOE 2WD</option>
<option value="gmc1500yukon2wd">GM C1500 YUKON 2WD</option>
<option value="gmcobalt">GM COBALT</option>
<option value="gmcolorado2wd">GM COLORADO 2WD</option>
<option value="gmcolorado4wd">GM COLORADO 4WD</option>
<option value="gmcoloradocabchassisinc2wd">GM COLORADO CAB CHASSIS INC 2WD</option>
<option value="gmcoloradocrewcab2wd">GM COLORADO CREW CAB 2WD</option>
<option value="gmcoloradocrewcab4wd">GM COLORADO CREW CAB 4WD</option>
<option value="gmcorvette">GM CORVETTE</option>
<option value="gmcts">GM CTS</option>
<option value="gmdts">GM DTS</option>
<option value="gmenvoy2wd">GM ENVOY 2WD</option>
<option value="gmenvoyxl4wd">GM ENVOY XL 4WD</option>
<option value="gmequinoxawd">GM EQUINOX AWD</option>
<option value="gmequinoxfwd">GM EQUINOX FWD</option>
<option value="gmescalade2wd">GM ESCALADE 2WD</option>
<option value="gmescaladeesvawd">GM ESCALADE ESV AWD</option>
<option value="gmg15/25chevvan2wdconv">GM G15/25CHEV VAN 2WD CONV</option>
<option value="gmg1500/2500chevyexpress2wd">GM G1500/2500 CHEVY EXPRESS 2WD</option>
<option value="gmg6">GM G6</option>
<option value="gmg6gt/gtpconvertible">GM G6 GT/GTP CONVERTIBLE</option>
<option value="gmgrandprix">GM GRAND PRIX</option>
<option value="gmh34wd">GM H3 4WD</option>
<option value="gmhhrfwd">GM HHR FWD</option>
<option value="gmi-2802wdextcab">GM I-280 2WD EXT CAB</option>
<option value="gmimpala">GM IMPALA</option>
<option value="gmk15silveradohybrid4wd">GM K15 SILVERADO HYBRID 4WD</option>
<option value="gmk1500silverado4wd">GM K1500 SILVERADO 4WD</option>
<option value="gmk1500tahoe4wd">GM K1500 TAHOE 4WD</option>
<option value="gmlacrosse/allure">GM LACROSSE/ALLURE</option>
<option value="gmlimousine">GM LIMOUSINE</option>
<option value="gmmalibu">GM MALIBU</option>
<option value="gmmontanasv6awd">GM MONTANA SV6 AWD</option>
<option value="gmrendezvousawd">GM RENDEZVOUS AWD</option>
<option value="gmrendezvousfwd">GM RENDEZVOUS FWD</option>
<option value="gmsolstice">GM SOLSTICE</option>
<option value="gmsrx2wd">GM SRX 2WD</option>
<option value="gmsrxawd">GM SRX AWD</option>
<option value="gmssrpickup2wd">GM SSR PICKUP 2WD</option>
<option value="gmsts">GM STS</option>
<option value="gmstsawd">GM STS AWD</option>
<option value="gmterrazafwd">GM TERRAZA FWD</option>
<option value="gmtrailblazer2wd">GM TRAILBLAZER 2WD</option>
<option value="gmtrailblazer4wd">GM TRAILBLAZER 4WD</option>
<option value="gmtrailblazerawd">GM TRAILBLAZER AWD</option>
<option value="gmuplanderfwd">GM UPLANDER FWD</option>
<option value="gmvueawd">GM VUE AWD</option>
<option value="gmvuefwd">GM VUE FWD</option>
<option value="gmxlr">GM XLR</option>
<option value="gmdaewooaveo">GM Daewoo  AVEO</option>
<option value="gmdaewooforenzawagon">GM Daewoo  FORENZA WAGON</option>
<option value="hondaaccord">HONDA ACCORD</option>
<option value="hondaaccordhybrid">HONDA ACCORD HYBRID</option>
<option value="hondacivic">HONDA CIVIC</option>
<option value="hondacivichybrid">HONDA CIVIC HYBRID</option>
<option value="hondacr-v2wd">HONDA CR-V 2WD</option>
<option value="hondacr-v4wd">HONDA CR-V 4WD</option>
<option value="hondaelement2wd">HONDA ELEMENT 2WD</option>
<option value="hondaelement4wd">HONDA ELEMENT 4WD</option>
<option value="hondamdx4wd">HONDA MDX 4WD</option>
<option value="hondaodyssey2wd">HONDA ODYSSEY 2WD</option>
<option value="hondapilot2wd">HONDA PILOT 2WD</option>
<option value="hondapilot4wd">HONDA PILOT 4WD</option>
<option value="hondaridgeline4wd">HONDA RIDGELINE 4WD</option>
<option value="hondarl">HONDA RL</option>
<option value="hondarsx">HONDA RSX</option>
<option value="hondas2000">HONDA S2000</option>
<option value="hondatl">HONDA TL</option>
<option value="hondatsx">HONDA TSX</option>
<option value="hyundaiaccent">HYUNDAI ACCENT</option>
<option value="hyundaiazera">HYUNDAI AZERA</option>
<option value="hyundaielantra">HYUNDAI ELANTRA</option>
<option value="hyundaisantafe2wd">HYUNDAI SANTAFE 2WD</option>
<option value="hyundaisantafe4wd">HYUNDAI SANTAFE 4WD</option>
<option value="hyundaisonata">HYUNDAI SONATA</option>
<option value="hyundaitucson2wd">HYUNDAI TUCSON 2WD</option>
<option value="hyundaitucson4wd">HYUNDAI TUCSON 4WD</option>
<option value="jaguarcarsincjaguars-type3.0litre">JAGUAR CARS INC JAGUAR S-TYPE 3.0 LITRE</option>
<option value="jaguarcarsincjaguars-type4.2litre">JAGUAR CARS INC JAGUAR S-TYPE 4.2 LITRE</option>
<option value="jaguarcarsincjaguars-typer">JAGUAR CARS INC JAGUAR S-TYPE R</option>
<option value="jaguarcarsincjaguarvdplwb">JAGUAR CARS INC JAGUAR VDP LWB</option>
<option value="jaguarcarsincjaguarx-type">JAGUAR CARS INC JAGUAR X-TYPE</option>
<option value="jaguarcarsincjaguarx-typesportbrake">JAGUAR CARS INC JAGUAR X-TYPE SPORT BRAKE</option>
<option value="jaguarcarsincjaguarxj8">JAGUAR CARS INC JAGUAR XJ8</option>
<option value="jaguarcarsincjaguarxk8convertible">JAGUAR CARS INC JAGUAR XK8 CONVERTIBLE</option>
<option value="jaguarcarsincjaguarxkrconvertible">JAGUAR CARS INC JAGUAR XKR CONVERTIBLE</option>
<option value="kiamotorscorporationkiaamanti">KIA MOTORS CORPORATION KIA AMANTI</option>
<option value="kiamotorscorporationkiaoptima">KIA MOTORS CORPORATION KIA OPTIMA</option>
<option value="kiamotorscorporationkiaoptima(ms)">KIA MOTORS CORPORATION KIA OPTIMA(MS)</option>
<option value="kiamotorscorporationkiario">KIA MOTORS CORPORATION KIA RIO</option>
<option value="kiamotorscorporationkiasedona">KIA MOTORS CORPORATION KIA SEDONA</option>
<option value="kiamotorscorporationkiasorento2wd">KIA MOTORS CORPORATION KIA SORENTO 2WD</option>
<option value="kiamotorscorporationkiasorento4wd">KIA MOTORS CORPORATION KIA SORENTO 4WD</option>
<option value="kiamotorscorporationkiaspectra(ld)">KIA MOTORS CORPORATION KIA SPECTRA(LD)</option>
<option value="kiamotorscorporationkiasportage2wd">KIA MOTORS CORPORATION KIA SPORTAGE 2WD</option>
<option value="kiamotorscorporationkiasportage4wd">KIA MOTORS CORPORATION KIA SPORTAGE 4WD</option>
<option value="lamborghinil-147/148murcielago">LAMBORGHINI L-147/148 MURCIELAGO</option>
<option value="lamborghini">LAMBORGHINI</option>
<option value="landroverlr3">LAND ROVER LR3</option>
<option value="landroverrangerover">LAND ROVER RANGE ROVER</option>
<option value="landroverrangeroversport">LAND ROVER RANGE ROVER SPORT</option>
<option value="lotuselise/exige">LOTUS ELISE/EXIGE</option>
<option value="maseraticoupecambiocorsa/gt/g-sport">MASERATI COUPE CAMBIOCORSA/GT/G-SPORT</option>
<option value="maseratimaseratiquattroporte">MASERATI MASERATI QUATTROPORTE</option>
<option value="mazdamotorcorp.mazda3">MAZDA MOTOR CORP. MAZDA 3</option>
<option value="mazdamotorcorp.mazda5">MAZDA MOTOR CORP. MAZDA 5</option>
<option value="mazdamotorcorp.mazda6">MAZDA MOTOR CORP. MAZDA 6</option>
<option value="mazdamotorcorp.mazda6sportwagon">MAZDA MOTOR CORP. MAZDA 6 SPORT WAGON</option>
<option value="mazdamotorcorp.mazdarx-8">MAZDA MOTOR CORP. MAZDA RX-8</option>
<option value="mazdamotorcorp.mpv">MAZDA MOTOR CORP. MPV</option>
<option value="mazdamotorcorp.mx-5">MAZDA MOTOR CORP. MX-5</option>
<option value="mercedesbenzc230">MERCEDES BENZ C230</option>
<option value="mercedesbenzc280">MERCEDES BENZ C280</option>
<option value="mercedesbenzc2804matic">MERCEDES BENZ C280 4MATIC</option>
<option value="mercedesbenzc3504matic">MERCEDES BENZ C350 4MATIC</option>
<option value="mercedesbenzc55amg">MERCEDES BENZ C55 AMG</option>
<option value="mercedesbenzcl65amg">MERCEDES BENZ CL65 AMG</option>
<option value="mercedesbenzclk350">MERCEDES BENZ CLK350</option>
<option value="mercedesbenzclk350(cabriolet)">MERCEDES BENZ CLK350 (CABRIOLET)</option>
<option value="mercedesbenzclk55amg(cabriolet)">MERCEDES BENZ CLK55 AMG (CABRIOLET)</option>
<option value="mercedesbenzcls500">MERCEDES BENZ CLS500</option>
<option value="mercedesbenzcls55amg">MERCEDES BENZ CLS55 AMG</option>
<option value="mercedesbenze320cdi">MERCEDES BENZ E320 CDI</option>
<option value="mercedesbenze350(wagon)">MERCEDES BENZ E350 (WAGON)</option>
<option value="mercedesbenze3504matic">MERCEDES BENZ E350 4MATIC</option>
<option value="mercedesbenze3504matic(wagon)">MERCEDES BENZ E350 4MATIC (WAGON)</option>
<option value="mercedesbenze500">MERCEDES BENZ E500</option>
<option value="mercedesbenze55amg">MERCEDES BENZ E55 AMG</option>
<option value="mercedesbenze55amg(wagon)">MERCEDES BENZ E55 AMG (WAGON)</option>
<option value="mercedesbenzmaybach57s">MERCEDES BENZ MAYBACH 57S</option>
<option value="mercedesbenzml350">MERCEDES BENZ ML350</option>
<option value="mercedesbenzml500">MERCEDES BENZ ML500</option>
<option value="mercedesbenzr350">MERCEDES BENZ R350</option>
<option value="mercedesbenzr500">MERCEDES BENZ R500</option>
<option value="mercedesbenzs430">MERCEDES BENZ S430</option>
<option value="mercedesbenzsl600">MERCEDES BENZ SL600</option>
<option value="mercedesbenzsl65amg">MERCEDES BENZ SL65 AMG</option>
<option value="mercedesbenzslk280">MERCEDES BENZ SLK280</option>
<option value="mercedesbenzslk350">MERCEDES BENZ SLK350</option>
<option value="mercedesbenzslr">MERCEDES BENZ SLR</option>
<option value="mitsubishieclipse">Mitsubishi  ECLIPSE</option>
<option value="mitsubishiendeavor2wd">Mitsubishi  ENDEAVOR 2WD</option>
<option value="mitsubishiendeavor4wd">Mitsubishi  ENDEAVOR 4WD</option>
<option value="mitsubishigalant">Mitsubishi  GALANT</option>
<option value="mitsubishilancer">Mitsubishi  LANCER</option>
<option value="mitsubishilancerevolution">Mitsubishi  LANCER EVOLUTION</option>
<option value="mitsubishilancersportback">Mitsubishi  LANCER SPORTBACK</option>
<option value="mitsubishimontero">Mitsubishi  MONTERO</option>
<option value="mitsubishioutlander2wd">Mitsubishi  OUTLANDER 2WD</option>
<option value="mitsubishioutlander4wd">Mitsubishi  OUTLANDER 4WD</option>
<option value="newunitedmotormfgincvibe">NEW UNITED MOTOR MFG INC VIBE</option>
<option value="nissan350z">Nissan 350Z</option>
<option value="nissan350zroadster">Nissan 350Z ROADSTER</option>
<option value="nissanaltima">Nissan ALTIMA</option>
<option value="nissanarmada2wd">Nissan ARMADA 2WD</option>
<option value="nissanarmada4wd">Nissan ARMADA 4WD</option>
<option value="nissanfrontierv6-2wd">Nissan FRONTIER V6-2WD</option>
<option value="nissanfrontierv6-4wd">Nissan FRONTIER V6-4WD</option>
<option value="nissanfx35rwd">Nissan FX35 RWD</option>
<option value="nissanfx45awd">Nissan FX45 AWD</option>
<option value="nissang35">Nissan G35</option>
<option value="nissanm35">Nissan M35</option>
<option value="nissanm35x">Nissan M35X</option>
<option value="nissanm45">Nissan M45</option>
<option value="nissanmaxima">Nissan MAXIMA</option>
<option value="nissanmuranoawd">Nissan MURANO AWD</option>
<option value="nissanmuranofwd">Nissan MURANO FWD</option>
<option value="nissanpathfinder2wd">Nissan PATHFINDER 2WD</option>
<option value="nissanpathfinder4wd">Nissan PATHFINDER 4WD</option>
<option value="nissanq45">Nissan Q45</option>
<option value="nissanq45sport">Nissan Q45 SPORT</option>
<option value="nissanquest">Nissan QUEST</option>
<option value="nissanqx564wd">Nissan QX56 4WD</option>
<option value="nissansentra">Nissan SENTRA</option>
<option value="nissantitan2wd">Nissan TITAN 2WD</option>
<option value="nissanxterra2wd">Nissan XTERRA 2WD</option>
<option value="nissanxterra4wd">Nissan XTERRA 4WD</option>
<option value="porscheboxster">PORSCHE BOXSTER</option>
<option value="porscheboxsters">PORSCHE BOXSTER S</option>
<option value="porschecarrera2coupe">PORSCHE CARRERA 2 COUPE</option>
<option value="porschecayenne">PORSCHE CAYENNE</option>
<option value="porschecayennes">PORSCHE CAYENNE S</option>
<option value="porschecayenneturbo">PORSCHE CAYENNE TURBO</option>
<option value="porschecaymans">PORSCHE CAYMAN S</option>
<option value="rolls-roycephantom">Rolls-Royce  PHANTOM</option>
<option value="rolls-royce">ROLLS-ROYCE</option>
<option value="roushindustries,inc.stage3f150supercrew4wd">Roush Industries, Inc. STAGE3 F150 SUPERCREW 4WD</option>
<option value="spykerautomobielenbvc8spyder">Spyker Automobielen BV C8 SPYDER</option>
<option value="suzukiaerio">SUZUKI AERIO</option>
<option value="suzukiaeriosx">SUZUKI AERIO SX</option>
<option value="suzukiaeriosxawd">SUZUKI AERIO SX AWD</option>
<option value="suzukigrandvitaraxl-7">SUZUKI GRAND VITARA XL-7</option>
<option value="suzukigrandvitaraxl-74wd">SUZUKI GRAND VITARA XL-7 4WD</option>
<option value="suzukigrandvitaraxv6">SUZUKI GRAND VITARA XV6</option>
<option value="suzuki">SUZUKI</option>
<option value="toyo">Toyo</option>
<option value="toyota4runner2wd">TOYOTA 4RUNNER 2WD</option>
<option value="toyota4runner4wd">TOYOTA 4RUNNER 4WD</option>
<option value="toyotaavalon">TOYOTA AVALON</option>
<option value="toyotacamry">TOYOTA CAMRY</option>
<option value="toyotacamrysolara">TOYOTA CAMRY SOLARA</option>
<option value="toyotacamrysolaraconvertible">TOYOTA CAMRY SOLARA CONVERTIBLE</option>
<option value="toyotacorolla">TOYOTA COROLLA</option>
<option value="toyotacorollamatrix">TOYOTA COROLLA MATRIX</option>
<option value="toyotaes330">TOYOTA ES 330</option>
<option value="toyotags3004wd">TOYOTA GS 300 4WD</option>
<option value="toyotags300/gs430">TOYOTA GS 300/GS 430</option>
<option value="toyotagx470">TOYOTA GX 470</option>
<option value="toyotahighlander2wd">TOYOTA HIGHLANDER 2WD</option>
<option value="toyotahighlander4wd">TOYOTA HIGHLANDER 4WD</option>
<option value="toyotahighlanderhybrid2wd">TOYOTA HIGHLANDER HYBRID 2WD</option>
<option value="toyotahighlanderhybrid4wd">TOYOTA HIGHLANDER HYBRID 4WD</option>
<option value="toyotais250">TOYOTA IS 250</option>
<option value="toyotais250awd">TOYOTA IS 250 AWD</option>
<option value="toyotais350">TOYOTA IS 350</option>
<option value="toyotals430">TOYOTA LS 430</option>
<option value="toyotalx470">TOYOTA LX 470</option>
<option value="toyotaprius">TOYOTA PRIUS</option>
<option value="toyotarav42wd">TOYOTA RAV4 2WD</option>
<option value="toyotarav44wd">TOYOTA RAV4 4WD</option>
<option value="toyotarx3302wd">TOYOTA RX 330 2WD</option>
<option value="toyotarx3304wd">TOYOTA RX 330 4WD</option>
<option value="toyotarx400h4wd">TOYOTA RX 400H 4WD</option>
<option value="toyotasc430">TOYOTA SC 430</option>
<option value="toyotasciontc">TOYOTA SCION TC</option>
<option value="toyotascionxa">TOYOTA SCION XA</option>
<option value="toyotascionxb">TOYOTA SCION XB</option>
<option value="toyotasequoia2wd">TOYOTA SEQUOIA 2WD</option>
<option value="toyotasequoia4wd">TOYOTA SEQUOIA 4WD</option>
<option value="toyotasienna2wd">TOYOTA SIENNA 2WD</option>
<option value="toyotatoyotatacoma2wd">TOYOTA TOYOTA TACOMA 2WD</option>
<option value="toyotatoyotatacoma4wd">TOYOTA TOYOTA TACOMA 4WD</option>
<option value="toyotatoyotatundra2wd">TOYOTA TOYOTA TUNDRA 2WD</option>
<option value="toyotatoyotatundra4wd">TOYOTA TOYOTA TUNDRA 4WD</option>
<option value="toyotayaris">TOYOTA YARIS</option>
<option value="volkswagena3quattro">VOLKSWAGEN A3 QUATTRO</option>
<option value="volkswagenjetta">VOLKSWAGEN JETTA</option>
<option value="volkswagennewbeetle">VOLKSWAGEN NEW BEETLE</option>
<option value="volkswagennewbeetleconvertible">VOLKSWAGEN NEW BEETLE CONVERTIBLE</option>
<option value="volkswagenpassatwagon4motion">VOLKSWAGEN PASSAT WAGON 4MOTION</option>
<option value="volkswagenphaeton">VOLKSWAGEN PHAETON</option>
<option value="volkswagenrabbit">VOLKSWAGEN RABBIT</option>
<option value="volkswagentouareg">VOLKSWAGEN TOUAREG</option>
<option value="volkswagenttcoupequattro">VOLKSWAGEN TT COUPE QUATTRO</option>
<option value="volkswagenttroadsterquattro">VOLKSWAGEN TT ROADSTER QUATTRO</option>
<option value="volvos40awd">VOLVO S40 AWD</option>
<option value="volvos40fwd">VOLVO S40 FWD</option>
<option value="volvos60awd">VOLVO S60 AWD</option>
<option value="volvos60fwd">VOLVO S60 FWD</option>
<option value="volvos60rawd">VOLVO S60 R AWD</option>
<option value="volvos80fwd">VOLVO S80 FWD</option>
<option value="volvov70fwd">VOLVO V70 FWD</option>
<option value="volvov70rawd">VOLVO V70 R AWD</option>
<option value="volvoxc70awd">VOLVO XC 70 AWD</option>
<option value="volvoxc90awd">VOLVO XC 90 AWD</option>
<option value="volvoxc90fwd">VOLVO XC 90 FWD</option>
<option value="volvonewc70convertible">VOLVO  NEW C70 CONVERTIBLE</option>
</select>
<br></br>
Your City in NJ: <select name="`city/town`" aria-required="true">
		<option value="absecon">Absecon</option>
<option value="allamuchy">Allamuchy</option>
<option value="allendale">Allendale</option>
<option value="allenhurst">Allenhurst</option>
<option value="allentown">Allentown</option>
<option value="allenwood">Allenwood</option>
<option value="alloway">Alloway</option>
<option value="alpine">Alpine</option>
<option value="andover">Andover</option>
<option value="annandale">Annandale</option>
<option value="asbury">Asbury</option>
<option value="asburypark">Asbury Park</option>
<option value="atco">Atco</option>
<option value="atlantichighlands">Atlantic Highlands</option>
<option value="audubon">Audubon</option>
<option value="augusta">Augusta</option>
<option value="avalon">Avalon</option>
<option value="avenel">Avenel</option>
<option value="avonbythesea">Avon By The Sea</option>
<option value="barnegat">Barnegat</option>
<option value="barnegatlight">Barnegat Light</option>
<option value="barrington">Barrington</option>
<option value="baskingridge">Basking Ridge</option>
<option value="bassriver">Bass River</option>
<option value="bayonne">Bayonne</option>
<option value="bayville">Bayville</option>
<option value="beachhaven">Beach Haven</option>
<option value="beachwood">Beachwood</option>
<option value="bedminster">Bedminster</option>
<option value="bellmawr">Bellmawr</option>
<option value="belmar">Belmar</option>
<option value="bergenfield">Bergenfield</option>
<option value="berkeley">Berkeley</option>
<option value="berkeleyheights">Berkeley Heights</option>
<option value="berlin">Berlin</option>
<option value="bernards">Bernards</option>
<option value="bernardsville">Bernardsville</option>
<option value="beverly">Beverly</option>
<option value="birmingham">Birmingham</option>
<option value="blackwood">Blackwood</option>
<option value="blairstown">Blairstown</option>
<option value="blawenburg">Blawenburg</option>
<option value="bloomfield">Bloomfield</option>
<option value="bloomingdale">Bloomingdale</option>
<option value="bloomsbury">Bloomsbury</option>
<option value="bogota">Bogota</option>
<option value="boonton">Boonton</option>
<option value="bordentown">Bordentown</option>
<option value="boundbrook">Bound Brook</option>
<option value="bradleybeach">Bradley Beach</option>
<option value="branchville">Branchville</option>
<option value="brick">Brick</option>
<option value="bridgeport">Bridgeport</option>
<option value="bridgeton">Bridgeton</option>
<option value="bridgewater">Bridgewater</option>
<option value="brielle">Brielle</option>
<option value="brigantine">Brigantine</option>
<option value="broadway">Broadway</option>
<option value="brownsmills">Browns Mills</option>
<option value="buddlake">Budd Lake</option>
<option value="buena">Buena</option>
<option value="burlington">Burlington</option>
<option value="butler">Butler</option>
<option value="buttzville">Buttzville</option>
<option value="caldwell">Caldwell</option>
<option value="califon">Califon</option>
<option value="capemay">Cape May</option>
<option value="capemaycourthouse">Cape May Court House</option>
<option value="capemaypoint">Cape May Point</option>
<option value="carlstadt">Carlstadt</option>
<option value="carteret">Carteret</option>
<option value="cedargrove">Cedar Grove</option>
<option value="cedarknolls">Cedar Knolls</option>
<option value="cedarville">Cedarville</option>
<option value="changewater">Changewater</option>
<option value="chatham">Chatham</option>
<option value="chatsworth">Chatsworth</option>
<option value="chester">Chester</option>
<option value="city/town">city/town</option>
<option value="clark">Clark</option>
<option value="clarksboro">Clarksboro</option>
<option value="clarksburg">Clarksburg</option>
<option value="clayton">Clayton</option>
<option value="clementon">Clementon</option>
<option value="cliffsidepark">Cliffside Park</option>
<option value="clifton">Clifton</option>
<option value="clinton">Clinton</option>
<option value="closter">Closter</option>
<option value="cologne">Cologne</option>
<option value="coltsneck">Colts Neck</option>
<option value="columbia">Columbia</option>
<option value="columbus">Columbus</option>
<option value="cookstown">Cookstown</option>
<option value="cranbury">Cranbury</option>
<option value="cranford">Cranford</option>
<option value="creamridge">Cream Ridge</option>
<option value="cresskill">Cresskill</option>
<option value="deepwater">Deepwater</option>
<option value="deerfieldstreet">Deerfield Street</option>
<option value="delaware">Delaware</option>
<option value="delmont">Delmont</option>
<option value="demarest">Demarest</option>
<option value="denville">Denville</option>
<option value="dividingcreek">Dividing Creek</option>
<option value="dorchester">Dorchester</option>
<option value="dorothy">Dorothy</option>
<option value="dover">Dover</option>
<option value="downe">Downe</option>
<option value="dumont">Dumont</option>
<option value="dunellen">Dunellen</option>
<option value="eastamwell">East Amwell</option>
<option value="eastbrunswick">East Brunswick</option>
<option value="eastorange">East Orange</option>
<option value="edgewater">Edgewater</option>
<option value="edison">Edison</option>
<option value="eggharborcity">Egg Harbor City</option>
<option value="eggharbortownship">Egg Harbor Township</option>
<option value="elizabeth">Elizabeth</option>
<option value="elmer">Elmer</option>
<option value="elmwoodpark">Elmwood Park</option>
<option value="elwood">Elwood</option>
<option value="elwood-magnolia">Elwood-Magnolia</option>
<option value="emerson">Emerson</option>
<option value="englewoodcliffs">Englewood Cliffs</option>
<option value="englishtown">Englishtown</option>
<option value="essexfells">Essex Fells</option>
<option value="estellmanor">Estell Manor</option>
<option value="ewan">Ewan</option>
<option value="fairhaven">Fair Haven</option>
<option value="fairlawn">Fair Lawn</option>
<option value="fairfield">Fairfield</option>
<option value="fairton">Fairton</option>
<option value="fairview">Fairview</option>
<option value="fanwood">Fanwood</option>
<option value="flagtown">Flagtown</option>
<option value="flanders">Flanders</option>
<option value="flemington">Flemington</option>
<option value="florence">Florence</option>
<option value="fords">Fords</option>
<option value="forkedriver">Forked River</option>
<option value="fortlee">Fort Lee</option>
<option value="fortmonmouth">Fort Monmouth</option>
<option value="fortescue">Fortescue</option>
<option value="franklin">Franklin</option>
<option value="franklinlakes">Franklin Lakes</option>
<option value="franklinpark">Franklin Park</option>
<option value="franklinville">Franklinville</option>
<option value="frenchtown">Frenchtown</option>
<option value="garfield">Garfield</option>
<option value="garwood">Garwood</option>
<option value="gibbsboro">Gibbsboro</option>
<option value="gibbstown">Gibbstown</option>
<option value="gillette">Gillette</option>
<option value="gladstone">Gladstone</option>
<option value="glasser">Glasser</option>
<option value="glengardner">Glen Gardner</option>
<option value="glenridge">Glen Ridge</option>
<option value="glendora">Glendora</option>
<option value="glenwood">Glenwood</option>
<option value="gloucestercity">Gloucester City</option>
<option value="goshen">Goshen</option>
<option value="greatmeadows">Great Meadows</option>
<option value="greencreek">Green Creek</option>
<option value="greenvillage">Green Village</option>
<option value="greendell">Greendell</option>
<option value="greenwich">Greenwich</option>
<option value="grenloch">Grenloch</option>
<option value="hackensack">Hackensack</option>
<option value="hackettstown">Hackettstown</option>
<option value="haddonheights">Haddon Heights</option>
<option value="haddonfield">Haddonfield</option>
<option value="hamburg">Hamburg</option>
<option value="hammonton">Hammonton</option>
<option value="hampton">Hampton</option>
<option value="hancocksbridge">Hancocks Bridge</option>
<option value="harringtonpark">Harrington Park</option>
<option value="harrisonville">Harrisonville</option>
<option value="hasbrouckheights">Hasbrouck Heights</option>
<option value="haskell">Haskell</option>
<option value="hawthorne">Hawthorne</option>
<option value="hazlet">Hazlet</option>
<option value="helmetta">Helmetta</option>
<option value="hewitt">Hewitt</option>
<option value="hibernia">Hibernia</option>
<option value="highlandlakes">Highland Lakes</option>
<option value="highlandpark">Highland Park</option>
<option value="highlands">Highlands</option>
<option value="hightstown">Hightstown</option>
<option value="hillsdale">Hillsdale</option>
<option value="hillside">Hillside</option>
<option value="hohokus">Ho Ho Kus</option>
<option value="ho-ho-kus">Ho-Ho-Kus</option>
<option value="holmdel">Holmdel</option>
<option value="hopatcong">Hopatcong</option>
<option value="hopewell">Hopewell</option>
<option value="howell">Howell</option>
<option value="imlaystown">Imlaystown</option>
<option value="ironia">Ironia</option>
<option value="irvington">Irvington</option>
<option value="iselin">Iselin</option>
<option value="jackson">Jackson</option>
<option value="jerseycity">Jersey City</option>
<option value="jobstown">Jobstown</option>
<option value="johnsonburg">Johnsonburg</option>
<option value="keansburg">Keansburg</option>
<option value="kearny">Kearny</option>
<option value="keasbey">Keasbey</option>
<option value="kendallpark">Kendall Park</option>
<option value="kenilworth">Kenilworth</option>
<option value="kenvil">Kenvil</option>
<option value="keyport">Keyport</option>
<option value="kingston">Kingston</option>
<option value="lafayette">Lafayette</option>
<option value="lakehiawatha">Lake Hiawatha</option>
<option value="lakehurst">Lakehurst</option>
<option value="lakewood">Lakewood</option>
<option value="lambertville">Lambertville</option>
<option value="landisville">Landisville</option>
<option value="lawnside">Lawnside</option>
<option value="layton">Layton</option>
<option value="lebanon">Lebanon</option>
<option value="ledgewood">Ledgewood</option>
<option value="leedspoint">Leeds Point</option>
<option value="leesburg">Leesburg</option>
<option value="leonia">Leonia</option>
<option value="libertycorner">Liberty Corner</option>
<option value="lincolnpark">Lincoln Park</option>
<option value="lincroft">Lincroft</option>
<option value="linden">Linden</option>
<option value="littlefalls">Little Falls</option>
<option value="littleferry">Little Ferry</option>
<option value="littlesilver">Little Silver</option>
<option value="littleyork">Little York</option>
<option value="longbranch">Long Branch</option>
<option value="longvalley">Long Valley</option>
<option value="longport">Longport</option>
<option value="lumberton">Lumberton</option>
<option value="lyndhurst">Lyndhurst</option>
<option value="lyons">Lyons</option>
<option value="madison">Madison</option>
<option value="magnolia">Magnolia</option>
<option value="mahwah">Mahwah</option>
<option value="malaga">Malaga</option>
<option value="manasquan">Manasquan</option>
<option value="mantoloking">Mantoloking</option>
<option value="manville">Manville</option>
<option value="mapleshade">Maple Shade</option>
<option value="margatecity">Margate City</option>
<option value="marlboro">Marlboro</option>
<option value="marlton">Marlton</option>
<option value="marmora">Marmora</option>
<option value="martinsville">Martinsville</option>
<option value="matawan">Matawan</option>
<option value="mauriceriver">Maurice River</option>
<option value="mayslanding">Mays Landing</option>
<option value="mcafee">McAfee</option>
<option value="medford">Medford</option>
<option value="mendham">Mendham</option>
<option value="merchantville">Merchantville</option>
<option value="metuchen">Metuchen</option>
<option value="mickleton">Mickleton</option>
<option value="middletown">Middletown</option>
<option value="middleville">Middleville</option>
<option value="midlandpark">Midland Park</option>
<option value="milford">Milford</option>
<option value="millburn">Millburn</option>
<option value="millington">Millington</option>
<option value="millstone">Millstone</option>
<option value="milltown">Milltown</option>
<option value="millville">Millville</option>
<option value="milmay">Milmay</option>
<option value="minehill">Mine Hill</option>
<option value="minotola">Minotola</option>
<option value="mizpah">Mizpah</option>
<option value="monmouthbeach">Monmouth Beach</option>
<option value="monroeville">Monroeville</option>
<option value="montague">Montague</option>
<option value="montclair">Montclair</option>
<option value="montvale">Montvale</option>
<option value="moonachie">Moonachie</option>
<option value="morganville">Morganville</option>
<option value="morrisplains">Morris Plains</option>
<option value="mountephraim">Mount Ephraim</option>
<option value="mountlaurel">Mount Laurel</option>
<option value="mountroyal">Mount Royal</option>
<option value="mounttabor">Mount Tabor</option>
<option value="mullicahill">Mullica Hill</option>
<option value="nationalpark">National Park</option>
<option value="navesink">Navesink</option>
<option value="neptune">Neptune</option>
<option value="netcong">Netcong</option>
<option value="newbrunswick">New Brunswick</option>
<option value="newgretna">New Gretna</option>
<option value="newlisbon">New Lisbon</option>
<option value="newmilford">New Milford</option>
<option value="newprovidence">New Providence</option>
<option value="newvernon">New Vernon</option>
<option value="newyork">New York</option>
<option value="newark">Newark</option>
<option value="newfield">Newfield</option>
<option value="newton">Newton</option>
<option value="norma">Norma</option>
<option value="northarlington">North Arlington</option>
<option value="northbergen">North Bergen</option>
<option value="northbrunswick">North Brunswick</option>
<option value="northfield">Northfield</option>
<option value="northvale">Northvale</option>
<option value="norwood">Norwood</option>
<option value="nutley">Nutley</option>
<option value="oakridge">Oak Ridge</option>
<option value="oakhurst">Oakhurst</option>
<option value="oakland">Oakland</option>
<option value="oaklyn">Oaklyn</option>
<option value="oceancity">Ocean City</option>
<option value="oceangate">Ocean Gate</option>
<option value="oceangrove">Ocean Grove</option>
<option value="oceanview">Ocean View</option>
<option value="oceanville">Oceanville</option>
<option value="ogdensburg">Ogdensburg</option>
<option value="oldbridge">Old Bridge</option>
<option value="oldwick">Oldwick</option>
<option value="oradell">Oradell</option>
<option value="orange">Orange</option>
<option value="oxford">Oxford</option>
<option value="palisadespark">Palisades Park</option>
<option value="palmyra">Palmyra</option>
<option value="paramus">Paramus</option>
<option value="parkridge">Park Ridge</option>
<option value="parlin">Parlin</option>
<option value="parsippany">Parsippany</option>
<option value="paterson">Paterson</option>
<option value="peapack">Peapack</option>
<option value="peapackandgladstone">Peapack and Gladstone</option>
<option value="pedricktown">Pedricktown</option>
<option value="pemberton">Pemberton</option>
<option value="pennington">Pennington</option>
<option value="pequannock">Pequannock</option>
<option value="perrineville">Perrineville</option>
<option value="perthamboy">Perth Amboy</option>
<option value="phillipsburg">Phillipsburg</option>
<option value="picatinnyarsenal">Picatinny Arsenal</option>
<option value="pinebeach">Pine Beach</option>
<option value="pinebrook">Pine Brook</option>
<option value="piscataway">Piscataway</option>
<option value="pitman">Pitman</option>
<option value="pittstown">Pittstown</option>
<option value="plainsboro">Plainsboro</option>
<option value="pleasantville">Pleasantville</option>
<option value="pointpleasantbeach">Point Pleasant Beach</option>
<option value="pomona">Pomona</option>
<option value="pomptonlakes">Pompton Lakes</option>
<option value="pomptonplains">Pompton Plains</option>
<option value="portelizabeth">Port Elizabeth</option>
<option value="portmonmouth">Port Monmouth</option>
<option value="portmurray">Port Murray</option>
<option value="portnorris">Port Norris</option>
<option value="portreading">Port Reading</option>
<option value="portrepublic">Port Republic</option>
<option value="pottersville">Pottersville</option>
<option value="princeton">Princeton</option>
<option value="princetonjunction">Princeton Junction</option>
<option value="quinton">Quinton</option>
<option value="ramsey">Ramsey</option>
<option value="rancocas">Rancocas</option>
<option value="randolph">Randolph</option>
<option value="raritan">Raritan</option>
<option value="readington">Readington</option>
<option value="redbank">Red Bank</option>
<option value="richland">Richland</option>
<option value="richwood">Richwood</option>
<option value="ridgefieldpark">Ridgefield Park</option>
<option value="ridgewood">Ridgewood</option>
<option value="ringoes">Ringoes</option>
<option value="ringwood">Ringwood</option>
<option value="riveredge">River Edge</option>
<option value="riverside">Riverside</option>
<option value="riverton">Riverton</option>
<option value="rochellepark">Rochelle Park</option>
<option value="rockyhill">Rocky Hill</option>
<option value="roebling">Roebling</option>
<option value="roosevelt">Roosevelt</option>
<option value="roseland">Roseland</option>
<option value="roselle">Roselle</option>
<option value="rosellepark">Roselle Park</option>
<option value="rosemont">Rosemont</option>
<option value="rosenhayn">Rosenhayn</option>
<option value="rumson">Rumson</option>
<option value="runnemede">Runnemede</option>
<option value="rutherford">Rutherford</option>
<option value="saddleriver">Saddle River</option>
<option value="salem">Salem</option>
<option value="sayreville">Sayreville</option>
<option value="schooleysmountain">Schooleys Mountain</option>
<option value="scotchplains">Scotch Plains</option>
<option value="seagirt">Sea Girt</option>
<option value="seaislecity">Sea Isle City</option>
<option value="seasideheights">Seaside Heights</option>
<option value="secaucus">Secaucus</option>
<option value="sergeantsville">Sergeantsville</option>
<option value="sewaren">Sewaren</option>
<option value="sewell">Sewell</option>
<option value="shorthills">Short Hills</option>
<option value="shrewsbury">Shrewsbury</option>
<option value="sicklerville">Sicklerville</option>
<option value="somerdale">Somerdale</option>
<option value="somerspoint">Somers Point</option>
<option value="somerset">Somerset</option>
<option value="southamboy">South Amboy</option>
<option value="southboundbrook">South Bound Brook</option>
<option value="southdennis">South Dennis</option>
<option value="southorange">South Orange</option>
<option value="southplainfield">South Plainfield</option>
<option value="southriver">South River</option>
<option value="southseaville">South Seaville</option>
<option value="springlake">Spring Lake</option>
<option value="springfield">Springfield</option>
<option value="stanhope">Stanhope</option>
<option value="stanton">Stanton</option>
<option value="stewartsville">Stewartsville</option>
<option value="stockton">Stockton</option>
<option value="stoneharbor">Stone Harbor</option>
<option value="strathmere">Strathmere</option>
<option value="succasunna">Succasunna</option>
<option value="summit">Summit</option>
<option value="swartswood">Swartswood</option>
<option value="swedesboro">Swedesboro</option>
<option value="teaneck">Teaneck</option>
<option value="tenafly">Tenafly</option>
<option value="tennent">Tennent</option>
<option value="teterboro">Teterboro</option>
<option value="threebridges">Three Bridges</option>
<option value="titusville">Titusville</option>
<option value="tomsriver">Toms River</option>
<option value="totowa">Totowa</option>
<option value="towaco">Towaco</option>
<option value="tranquility">Tranquility</option>
<option value="tuckahoe">Tuckahoe</option>
<option value="tuckerton">Tuckerton</option>
<option value="union">Union</option>
<option value="unioncity">Union City</option>
<option value="vauxhall">Vauxhall</option>
<option value="vernon">Vernon</option>
<option value="verona">Verona</option>
<option value="vienna">Vienna</option>
<option value="vincentown">Vincentown</option>
<option value="vineland">Vineland</option>
<option value="voorhees">Voorhees</option>
<option value="waldwick">Waldwick</option>
<option value="wallington">Wallington</option>
<option value="wallpackcenter">Wallpack Center</option>
<option value="wanaque">Wanaque</option>
<option value="waretown">Waretown</option>
<option value="warren">Warren</option>
<option value="washington">Washington</option>
<option value="waterfordworks">Waterford Works</option>
<option value="wayne">Wayne</option>
<option value="westberlin">West Berlin</option>
<option value="westcreek">West Creek</option>
<option value="westlongbranch">West Long Branch</option>
<option value="westnewyork">West New York</option>
<option value="westorange">West Orange</option>
<option value="westfield">Westfield</option>
<option value="westville">Westville</option>
<option value="westwood">Westwood</option>
<option value="whitehousestation">Whitehouse Station</option>
<option value="whitesboro">Whitesboro</option>
<option value="whiting">Whiting</option>
<option value="wickatunk">Wickatunk</option>
<option value="wildwood">Wildwood</option>
<option value="williamstown">Williamstown</option>
<option value="willingboro">Willingboro</option>
<option value="windsor">Windsor</option>
<option value="woodridge">Wood Ridge</option>
<option value="woodbine">Woodbine</option>
<option value="woodbridge">Woodbridge</option>
<option value="woodbury">Woodbury</option>
<option value="woodburyheights">Woodbury Heights</option>
<option value="woodclifflake">Woodcliff Lake</option>
<option value="woodstown">Woodstown</option>
<option value="wrightstown">Wrightstown</option>
<option value="wyckoff">Wyckoff </option>  
 </select> 
 
 Type:<select name="type">
	 <option value="12">Urban</option>
	 <option value="9">Subrban</option>
	 <option value="5">Rural</option>
 </select>
 
 Age: <select name="age" id="day_ID" aria-required="true">
  <option value="100">17-21</option>
  <option value="80">22-30</option>
  <option value="40">31-40-</option>
  <option value="25">41-50</option>
  <option value="20">51-60</option>
  <option value="15">60+</option>
</select>

<br></br>
<input type="submit" value="Get My Insurance Premium" >
</form>

<!-- <script type="text/javascript" language="javascript">
    function checkform()
    {
        var f = document.forms["insert"].elements;
        var cansubmit = true;

        for (var i = 0; i < f.length; i++) {
            if (f[i].value.length == 0) cansubmit = false;
        }

        document.getElementById('submit').disabled = !cansubmit;
    }
</script> -->
<br></br>
<p><font size="5"><u>Please report a car accident here!</u></font></p>
 <br>
	<form name="insert" method="post" action="newBeer.jsp" align="center">
	<table align="center">
	<tr>
	<td>Make/Model:</td><td><input type="text" name="`make/model`"></td>

	<td>Car Year:</td><td><input type="text" name="year"></td>

	<td>Safety Rating:</td><td><select name="safety_rating"  aria-required="true">
		<option value="1">*</option>
  		<option value="2">**</option>
  		<option value="3">***</option>
  		<option value="4">****</option>
  		<option value="5">*****</option>
</option>
</select></td>
	</tr>
	<tr>
	<td>Accident_History:</td><td><select name="accident_history"  aria-required="true">
		<option value="TRUE">Yes</option>
  		<option value="FALSE">No</option>
</option>
</select> </td>
<td>DUI:</td><td><select name="DUI"  aria-required="true">
		<option value="TRUE">Under the Influence</option>
  		<option value="FALSE">Sober</option>
</option>
</select> </td>
<td>Gender:</td><td><select name="gender"  aria-required="true">
		<option value="male">Male</option>
  		<option value="female">Female</option>
</option>
<tr>
</select> </td>
<td>Day: </td><td><select name="day" id="day_ID" aria-required="true">
  <option value="01">01</option>
  <option value="02">02</option>
  <option value="03">03</option>
  <option value="04">04</option>
	  <option value="05">05</option>
  <option value="06">06</option>
  <option value="07">07</option>
  <option value="08">08</option>
	  <option value="09">09</option>
  <option value="10">10</option>
  <option value="11">11</option>
  <option value="12">12</option>
	  <option value="13">13</option>
  <option value="14">14</option>
  <option value="15">15</option>
  <option value="16">16</option>
	  <option value="17">17</option>
  <option value="18">18</option>
  <option value="19">19</option>
  <option value="20">20</option>
	   <option value="21">21</option>
  <option value="22">22</option>
  <option value="23">23</option>
  <option value="24">24</option>
	  <option value="25">25</option>
  <option value="26">26</option>
  <option value="27">27</option>
  <option value="28">28</option>
	  <option value="29">29</option>
  <option value="30">30</option>
  <option value="31">31</option>
  </select> </td>
 <td> Month:</td> <td><select name="month" id="month_ID" aria-required="true">
  <option value="01">January</option>
  <option value="02">February</option>
  <option value="03">March</option>
  <option value="04">April</option>
	  <option value="05">May</option>
  <option value="06">June</option>
  <option value="07">July</option>
  <option value="08">August</option>
	  <option value="09">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
	  </select> </td>
	  
	<td>   Year:</td> <td><select name="year2" id="year_ID" aria-required="true">
  <option value="2012">2012</option>
  <option value="2013">2013</option>
  <option value="2014">2014</option>
  <option value="2015">2015</option>
</select></td>
<tr>
<td>Street/Highway:</td><td><input type="text" name="street"></td>

	<td>City: </td><td><input type="text" name="`city/town`"></td>
	
	<td>Driver's Age: </td><td>
	<select name="age" id="year_ID" aria-required="true">
  <option value="17">17</option>
  <option value="18">18</option>
  <option value="19">19</option>
  <option value="20">21</option>
  <option value="22">22</option>
  <option value="23">23</option>
  <option value="24">24</option>
  <option value="25">25</option>
  <option value="26">26</option>
  <option value="27">27</option>
  <option value="28">28</option>
  <option value="29">29</option>
  <option value="30">30</option>
  <option value="31">31</option>
  <option value="32">32</option>
  <option value="33">33</option>
  <option value="34">34</option>
  <option value="35">35</option>
  <option value="36">36</option>
  <option value="37">37</option>
  <option value="38">38</option>
  <option value="39">39</option>
  <option value="40">40</option>
  <option value="41">41</option>
  <option value="42">42</option>
  <option value="43">43</option>
  <option value="44">44</option>
  <option value="45">45</option>
  <option value="46">46</option>
  <option value="47">47</option>
  <option value="48">48</option>
  <option value="49">49</option>
  <option value="50">50</option>
  <option value="51">51</option>
  <option value="52">52</option>
  <option value="53">53</option>
  <option value="54">54</option>
  <option value="55">55</option>
  <option value="56">56</option>
  <option value="57">57</option>
  <option value="58">58</option>
  <option value="59">59</option>
  <option value="60">60</option>
  <option value="61">61</option>
  <option value="62">62</option>
  <option value="63">63</option>
  <option value="64">64</option>
  <option value="65">65</option>
  <option value="66">66</option>
  <option value="67">67</option>
  <option value="68">68</option>
  <option value="69">69</option>
  <option value="70">70</option>
  <option value="71">71</option>
  <option value="72">72</option>
  <option value="73">73</option>
  <option value="74">74</option>
  <option value="75">75</option>
  <option value="76">76</option>
  <option value="77">77</option>
  <option value="78">78</option>
  <option value="79">79</option>
  <option value="80">80</option>
  <option value="81">81</option>
  <option value="82">82</option>
  <option value="83">83</option>
  <option value="84">84</option>
  <option value="85">85</option>
  <option value="86">86</option>
  <option value="87">87</option>
  <option value="88">88</option>
  <option value="89">89</option>
  <option value="90">90</option>
  <option value="91">91</option>
  <option value="92">92</option>
  <option value="93">93</option>
  <option value="94">94</option>
  <option value="95">95</option>
  <option value="96">96</option>
  <option value="97">97</option>
  <option value="98">98</option>
  <option value="99">99</option>
  <option value="100">100</option>
  <option value="100">100+</option>
</select></td>
</tr>
	</tr>
	</table>
	<br> 
	<input type="submit" value="Submit Accident" >
	</form>
</body>
</html> 
